services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-mate #distribución linux
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - CUSTOM_USER=admin  #usuario
      - PASSWORD=p4ssw0rd  #contraseña
      - LC_ALL=es_ES.UTF-8
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - "3000:3000"
      - "3001:3001"
    shm_size: "1gb" #optional
    restart: unless-stopped

    
